INSERT INTO TIM.TIM_EMPLOYEES (ID,NAME,SURNAMES,CUSTOMER_HOUR_PRICE,EMPLOYEE_HOUR_PRICE) VALUES
	 (1,'JOSE MARIA','MARTINEZ LUNA',15.0,10.0),
	 (2,'ATANASIO','MUÑOZ GONZALEZ',15.0,10.0),
	 (3,'RAFAEL','LÓPEZ TORRES',15.0,10.0);