
-- -----------------------------------------------------
-- Table `TIM`.`BUDGETS`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `TIM`.`TIM_BUDGETS` (
  `UUID` UUID NOT NULL,
  `BUDGET_NUMBER` BIGINT NULL,
  `DESCRIPTION` VARCHAR(245) NULL,
  `DATE` DATE NULL,
  `YEAR` INT NULL,
  `EXPIRATION_DATE` DATE NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE INDEX `BUDGET_NUMBER_UNIQUE` (`BUDGET_NUMBER` ASC));

-- -----------------------------------------------------
-- Table `TIM`.`BUDGET_ITEMS`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `TIM`.`TIM_BUDGET_ITEMS` (
  `UUID` UUID NOT NULL,
  `BUDGET_UUID` UUID NOT NULL,
  `DESCRIPTION` VARCHAR(245) NULL,
  `AMOUNT` INT NULL,
  `PRICE` DOUBLE NULL,
  PRIMARY KEY (`UUID`),
  CONSTRAINT `fk_TIM_BUDGET_ITEMS_TIM_BUDGETS`
    FOREIGN KEY (`BUDGET_UUID`)
    REFERENCES `TIM`.`TIM_BUDGETS` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


INSERT INTO TIM.TIM_BUDGETS(UUID, BUDGET_NUMBER, DESCRIPTION, DATE, YEAR)  VALUES ('123e4567e89b12d3a456556642440000','30', 'Presupuesto 1', '2021-11-01', 2021);    
INSERT INTO TIM.TIM_BUDGETS(UUID, BUDGET_NUMBER, DESCRIPTION, DATE, YEAR)  VALUES ('123e4567e89b12d3a456556642440001','40', 'Presupuesto 2', '2021-11-02', 2021);
INSERT INTO TIM.TIM_BUDGETS(UUID, BUDGET_NUMBER, DESCRIPTION, DATE, YEAR)  VALUES ('123e4567e89b12d3a456556642440002','50', 'Presupuesto 3', '2021-11-03', 2021);