-- -----------------------------------------------------
-- Table `TIM`.`BUDGET_ITEMS`
-- -----------------------------------------------------
 
-- DROP TABLE `TIM`.`TIM_BUDGET_ITEMS`;
-- CREATE TABLE IF NOT EXISTS

CREATE TABLE IF NOT EXISTS `TIM`.`TIM_BUDGET_ITEMS` (
  `UUID` UUID NOT NULL,
  `BUDGET_UUID` UUID NOT NULL,
  `DESCRIPTION` VARCHAR(245) NULL,
  `AMOUNT` INT NULL,
  `PRICE` DOUBLE NULL,
  PRIMARY KEY (`UUID`),
  CONSTRAINT `fk_TIM_BUDGET_ITEMS_TIM_BUDGETS` FOREIGN KEY (`BUDGET_UUID`) REFERENCES `TIM`.`TIM_BUDGETS` (`UUID`));
 



-- CREATE TABLE IF NOT EXISTS `TIM`.`TIM_BUDGET_ITEMS` (
--  `UUID` UUID NOT NULL,
--  `BUDGETUUID` UUID NOT NULL,
--  `DESCRIPTION` VARCHAR(245) NULL,
--  `AMOUNT` INT NULL,
-- `PRICE` DOUBLE NULL,
--  PRIMARY KEY (`UUID`),
--  CONSTRAINT `fk_TIM_BUDGET_ITEMS_TIM_BUDGETS`
--    FOREIGN KEY (`BUDGETUUID`)
--    REFERENCES `TIM`.`TIM_BUDGETS` (`UUID`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION);
    
 -- INSERT INTO TIM.TIM_BUDGET_ITEMS(UUID, BUDGETUUID, DESCRIPTION, AMOUNT, PRICE)  VALUES ('123e4567e89b12d3a456556642440001','123e4567e89b12d3a456556642440005', 'Cajas de bombillas', 2, 5.0);
 
    INSERT INTO TIM.TIM_BUDGET_ITEMS(UUID, BUDGET_UUID, DESCRIPTION, AMOUNT, PRICE)  VALUES ('123e4567e89b12d3a456556642440001', '123e4567e89b12d3a456556642440000', 'Cajas de bombillas', 2, 5.0);
