CREATE TABLE IF NOT EXISTS `TIM`.`TIM_CUSTOMERS` (
  `DNI` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `SURNAMES` VARCHAR(45) NULL,
  `ADDRESS` VARCHAR(200) NULL,
  `PHONE` VARCHAR(10) NULL,
  `EMAIL` VARCHAR(100) NULL,
  `EXPIRATION_DATE` DATE NULL,
  PRIMARY KEY (`DNI`));


INSERT INTO TIM.TIM_CUSTOMERS(DNI, NAME, SURNAMES)  VALUES ('30', 'usuario 30', 'USUARIO 30');
INSERT INTO TIM.TIM_CUSTOMERS(DNI, NAME, SURNAMES)  VALUES ('40', 'usuario 40', 'USUARIO 40');
INSERT INTO TIM.TIM_CUSTOMERS(DNI, NAME, SURNAMES)  VALUES ('50', 'usuario 50', 'USUARIO 50');