--DROP TABLE if exists `TIM`.`TIM_BUDGET_ITEMS` cascade;
--DROP TABLE if exists `TIM`.`TIM_BUDGETS` cascade;
--DROP TABLE if exists `TIM`.`TIM_CUSTOMERS` cascade;

--DROP TABLE `TIM`.`TIM_BUDGET_ITEMS`;
-- DROP TABLE `TIM`.`TIM_CUSTOMERS`;
-- DROP TABLE `TIM`.`TIM_BUDGETS`;
DROP ALL OBJECTS;
CREATE SCHEMA IF NOT EXISTS TIM
