CREATE TABLE IF NOT EXISTS `TIM`.`TIM_EMPLOYEES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `SURNAMES` VARCHAR(100) NULL,
  `CUSTOMER_HOUR_PRICE` DOUBLE NULL,
  `EMPLOYEE_HOUR_PRICE` DOUBLE NULL,
  `EXPIRATION_DATE` DATE NULL,
  PRIMARY KEY (`ID`));


INSERT INTO TIM.TIM_EMPLOYEES(ID, NAME, SURNAMES, CUSTOMER_HOUR_PRICE, EMPLOYEE_HOUR_PRICE)  VALUES (1, 'usu1', 'usuario 1', 15, 10);
INSERT INTO TIM.TIM_EMPLOYEES(ID, NAME, SURNAMES, CUSTOMER_HOUR_PRICE, EMPLOYEE_HOUR_PRICE)  VALUES (2, 'usu2', 'usuario 2', 15, 10);
INSERT INTO TIM.TIM_EMPLOYEES(ID, NAME, SURNAMES, CUSTOMER_HOUR_PRICE, EMPLOYEE_HOUR_PRICE)  VALUES (3, 'usu3', 'usuario 3', 15, 10);
INSERT INTO TIM.TIM_EMPLOYEES(ID, NAME, SURNAMES, CUSTOMER_HOUR_PRICE, EMPLOYEE_HOUR_PRICE)  VALUES (4, 'usu4', 'usuario 4', 15, 10);
